# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/fastHTML_ds',
                'doc_host': 'https://Deufel.github.io',
                'git_url': 'https://github.com/Deufel/fastHTML_ds',
                'lib_path': 'fastHTML_ds'},
  'syms': { 'fastHTML_ds.core': { 'fastHTML_ds.core.FastHTML._endp': ('core.html#fasthtml._endp', 'fastHTML_ds/core.py'),
                                  'fastHTML_ds.core.FastHTML.route': ('core.html#fasthtml.route', 'fastHTML_ds/core.py'),
                                  'fastHTML_ds.core._datastar_part_resp': ('core.html#_datastar_part_resp', 'fastHTML_ds/core.py'),
                                  'fastHTML_ds.core._datastar_resp': ('core.html#_datastar_resp', 'fastHTML_ds/core.py'),
                                  'fastHTML_ds.core._datastar_xml': ('core.html#_datastar_xml', 'fastHTML_ds/core.py')}}}
